export const CITIES = [
  "Abbaspur", "Abbottabad", "Abdul Hakeem", "Adda Johal", "Adda One R",
  "Adda Panwan", "Adda Plot", "Adda Shaikh Wahan", "Adda Siraj", "Ahmad Nagar Chatha",
  "Ahmadal", "Ahmed Nagar", "Ahmedpur East", "Ahmedpur Sial", "Aimanabad Town",
  "Ajnia Wala", "Akhtar Abad", "Akora Khatak", "Akwal", "Ali Pur Bangla",
  "Alipur", "Alipur Chatha", "Allah Abad", "Amangarh", "Aminabad",
  "Aminpur Bangla", "Amra Kalan", "Amra Khurd", "Anwarabad", "Arifwala",
  "Arja", "Asharay", "Athmuqam", "Attock", "Attowala",
  "Ayubia", "Baddomalhi", "Badin", "Baffa", "Bagh",
  "Bahawalnagar", "Bahawalpur", "Bahrain", "Bahria Orchard", "Bahtar More",
  "Baidara", "Baig Pur", "Bajar Wala", "Balakot", "Balambat",
  "Ban Bajwa", "Bandhi", "Banguldero", "Bannu", "Bansra Gali",
  "Bara Manga", "Bara Market", "Barian", "Barikot", "Barkhan",
  "Barrth", "Basharat", "Basirpur", "Basti Malook", "Batkhela",
  "Battagram", "Begum Kot", "Beknanwala", "Bela", "Bhagowal Khurd",
  "Bhagtanwala", "Bhai Pheru", "Bhakkar", "Bhaknawali", "Bhal Syedan",
  "Bhalwaal", "Bhan Sayedabad", "Bhara Kahu", "Bhau Ghasitpur", "Bhera",
  "Bhikki", "Bhimber", "Bhoe Asal", "Bhoman Batth", "Bhopalwala",
  "Bhowana", "Bhurbun", "Bilalabad", "Birth Both", "Bonga Hayat",
  "Bosal", "Bozdar Wada", "Bucheke", "Buner", "Buni",
  "Burewala", "Cadet College Sunny Bank", "Canal City", "Chak Ali Shah", "Chak Beli Khan",
  "Chak Fateh Shah", "Chak Hamid", "Chak Jani", "Chak Jhumra", "Chak Parana",
  "Chak Shadi", "Chakdara", "Chaklala", "Chakori Bhilowal", "Chakri",
  "Chakswari", "Chakwal", "Chaman", "Chamankot", "Changa Manga",
  "Channan", "Char Bagh", "Charhoi", "Charsadda", "Chashma",
  "Chaubara", "Chawinda", "Chenab Nagar", "Chianwali", "Chichawatni",
  "Chikkar", "Chilas", "Chillianwala", "Chiniot", "Chinji",
  "Chishtian", "Chitral", "Chitta More", "Choa Khalsa", "Choa Saidan Shah",
  "Chobara", "Chor", "Chota Lahore", "Chota Sahiwal", "Chowk Azam",
  "Chowk Munda", "Chowk Pandori", "Chuhar Jamali", "Chunawala", "Chunian",
  "Dadu", "Dadyal", "Daggar", "Daghoni Balgar", "Dakwala",
  "Dambodas", "Danda Shah Bilawal", "Daood Zai", "Dargai", "Darman",
  "Darro", "Darya Gali", "Darya Khan", "Daska", "Daud Khel",
  "Daul Tala", "Daulatpur", "Daur", "Deharki", "Dehla Chattha",
  "Depalpur", "Dera Allah Yar", "Dera Ghazi Khan", "Dera Ismail Khan", "Dera Murad Jamali",
  "Dera Nawab", "Dewal", "Dewalay", "Dewana Baba", "Dhabjee",
  "Dhakkar", "Dharabi", "Dharyala Jalap", "Dheri Araian", "Dhirkot",
  "Dhoke Shahani", "Dhori Adda", "Dhudial", "Dhulian", "Dhurnal",
  "Digri", "Dijkot", "Dilawar Cheema", "Dina", "Dina Nath",
  "Dinga", "Distt. Complex", "Doaba", "Doberan Kallan", "Dokri",
  "Donga Bonga", "Doughal", "Drosh", "Dudhu Chak", "Dulle Wala",
  "Duniapur", "F.F.C. Plant", "Faisalabad", "Faqirwali", "Farhat Abad",
  "Faroka", "Farooqabad", "Fateh Jang", "Fateh Pur", "Fateh Pur Kamal",
  "Fatehpur Thakiala", "Fatta Bhand", "Fazil Pur", "Feroz Watwan", "Ferozewala",
  "Fkpcl Power Plant", "Fort Abbas", "Forward Kahuta", "Gagan", "Gaggo Mandi",
  "Gali Jagir", "Gamba Skardu", "Gambat", "Gamber", "Garh Maharaja",
  "Garh More", "Garha More", "Garhi Dupatta", "Garhi Mori", "Gatwala",
  "Ghakkar Mandi", "Ghari Habibullah", "Gharial Camp", "Gharibwal", "Gharo",
  "Ghazi", "Ghaziabad", "Ghika Gali", "Ghora Gali", "Ghotki",
  "Ghour Ghusti", "Ghous Pur", "Ghumman Wala", "Gilgit", "Gojra",
  "Golarchi", "Golpur", "Goth Machi", "Gujar Khan", "Gujranwala",
  "Gujrat", "Gulyana", "Gumti Shareef", "Gunja", "Gurmani Adda",
  "Gwadar", "Habib Abad", "Hafizabad", "Hajeera", "Hakim Abad",
  "Hala", "Hangu", "Haranpur", "Harappa", "Harighel",
  "Haripur", "Harnal", "Haroonabad", "Haseeb Waqas Mills", "Hasil Pur",
  "Haslanwala", "Hassan Abdal", "Hatia Bala", "Hattar", "Hattian Bala",
  "Haveli Bahadur Shah", "Haveli Lakha", "Havelian", "Hazara University", "Hazrat Kalianwala",
  "Hazro", "Head Baloki Road", "Head Khokhra", "Head Marala", "Hub",
  "Hujra Shah Mukeem", "Hunza–Nagar", "Husri", "Hussainabad", "Hyderabad",
  "Iikhlas", "Ikhlaspur", "Iqbal Abad", "Iqbal Nagar", "Islam Garh",
  "Islam Headworks", "Islamabad", "Islamgarh", "Jabbi Shah Dilawar", "Jacobabad",
  "Jafarabad", "Jaffar Mandi", "Jahanian", "Jalalpur Bhattian", "Jalalpur Jattan",
  "Jalalpur Sharif", "Jalalpurpirwala", "Jamalpur", "Jamke Chatha", "Jampur",
  "Jamshoro", "Jandia Sher Khan", "Jani Chak", "Janu Chak", "Jaranwala",
  "Jasial", "Jatlan (AJK)", "Jatoi", "Jaurah", "Jehangira",
  "Jhabran Mandi", "Jhang", "Jhelum", "Jhol", "Jhuddo",
  "Joharabad", "Johi", "Juglot", "Jutana", "Kabal",
  "Kabirwala", "Kacha Khoo", "Kachura", "Kadhan", "Kahauta",
  "Kahuta", "Kairpur Nathin Shah", "Kalaske Cheema", "Kalaswala", "Kali Mitti",
  "Kallar Kahar", "Kallar Syeddan", "Kalor Kot", "Kamalia", "Kamoke",
  "Kamra", "Kamrial", "Kand Kot", "Kandhkot", "Kandiaro",
  "Kangan Pur", "Kangra", "Kanju", "Kanoha", "Kanyal",
  "Kapco Power Plant", "Karachi", "Karachi Alhydri", "Karachi City", "Karachi Saddar",
  "Karak", "Karam Pur", "Karariwala Khurd", "Kariala Jalib", "Karoor Paka",
  "Karor Lal Easan", "Kartarpur", "Kashmir Point", "Kashmore", "Kassowal",
  "Kasur", "Kathore", "Keris", "Khai Gala", "Khairpur",
  "Khairpur Meerus", "Khairpur Nathan Shah", "Khairpur Tamewali", "Khan Bela", "Khan Ghar",
  "Khanewal", "Khanka Dogran", "Khanpur", "Khanpur Mahar", "Khaplu",
  "Kharala", "Kharian", "Kharmang", "Khas Behaal", "Khaur",
  "Khidarwala", "Khipro", "Khoaza Khaila", "Khohar", "Khori Alam",
  "Khoski", "Khudian Khas", "Khuhra", "Khuiratta", "Khunda",
  "Khurrianwala", "Khushab", "Khwazakhela", "Khwera", "Kingra Mor",
  "Kml Via Ccw", "Kohat", "Korangi Karachi", "Kot Abdul Malik", "Kot Addu",
  "Kot Aslam", "Kot Banglo", "Kot Baray Khan", "Kot Bilal", "Kot Chutta",
  "Kot Fateh Khan", "Kot Ghulam Muhammad", "Kot Mithan", "Kot Momin", "Kot Nainan",
  "Kot Pindi Das", "Kot Qadir Bakhsh", "Kot Qaisrani", "Kot Qazi", "Kot Radha Kishan",
  "Kot Samabah", "Kotanai", "Kotla Arab Ali Khan", "Kotli", "Kotli (AJK)",
  "Kotli Behram", "Kotli Loharan", "Kotri", "Kotri Muhammad Kabir", "Kuchlak",
  "Kulachi", "Kuldana", "Kulluwal", "Kumb", "Kundian",
  "Kunjah", "Kunri", "Kuthyala Syedan", "Ladha Sadha", "Ladhewala Cheema",
  "Lahore", "Lahore Cantt", "Laidher", "Lake City", "Lakha Road",
  "Lakhne Wala", "Lakki Marwat", "Lala Chak", "Lala Musa", "Lalian",
  "Lallian", "Lalliani", "Lalpir (thermal Power)", "Larkana", "Lasoori Kalan",
  "Lawa", "Lawrence Pur", "Layyah", "Lessar Kalan", "Liaqat National Bagh Aka Company Bagh",
  "Liaqat Pur", "Liaquatabad", "Lilla", "Lodhran", "Loralai",
  "Lower Bazar", "Lower Chitral", "Lower Dir", "Lower Topa", "Machikey",
  "Machiwal", "Madrassa Chattha", "Madyan", "Mailsi", "Maira Sharif",
  "Majju Chak", "Makli", "Malakand", "Malakwal", "Mamdot",
  "Mamu Kanjan", "Mana Wla", "Manawala", "Manchar Chattha", "Mandi Bahauddin",
  "Mandi Buchiana", "Mandi Safdar Abad", "Mandi Usman Wala", "Mandian", "Mandra",
  "Manga Mandi", "Mangat", "Mangla (AJK)", "Mangla Cantt (AJK)", "Mankera",
  "Mankyla Station", "Mansehra", "Manthal", "Mardan", "Mari",
  "Masar Camp", "Matiari", "Matli", "Matore", "Matta",
  "Mehar", "Mehdiabad", "Meher", "Mehmood Kot", "Mehrab Pur",
  "Mian Channu", "Mian Wali Qureshain", "Miana Gondal", "Miandam", "Miani",
  "Mianwali", "Mianwali Bangla", "Minchinabad", "Mingora", "Mir Pur Methelo",
  "Mirak Sial", "Mirpur", "Mirpur (AJK)", "Mirpur Bathoro", "Mirpur Khas",
  "Mirpur Mathelo", "Mirpur Sakro", "Mitha Tiwana", "Mithi", "Mitthi",
  "Mohalla Rajgan", "Mor Aimanabad", "More Aimanabad", "More Khunda", "Moro",
  "Motra", "Muhammad Panah Mor", "Multan", "Multan Khurd", "Munda",
  "Mundi Khel", "Murali", "Murali Wala", "Murat", "Muridke",
  "Murree", "Muzaffarabad", "Muzaffarabad (AJK)", "Muzaffargarh", "Nakka Kahut",
  "Nankana Sahib", "Nara", "Narang Mandi", "Narar", "Narowal",
  "Nasarpur", "Nasirabad", "Nathia Gali", "Naushahro Feroze", "Nawabshah",
  "Nawan Shehr", "Naway Kali", "Naya Lahore", "New Industrial Area", "New Murree",
  "New Town Karachi", "Nizamabad", "Nokhar", "Noman Pora", "Nonar",
  "Noor Colony", "Noor Jamaal", "Noor Kot", "Noorpur", "Noorpur Thal",
  "Noriabad", "Nowshera", "Nowshera Kalan", "Nowshera Virkan", "Nrtc (telecom Staff College)",
  "Nudearo", "Okara", "Old Hala", "Olding", "P.O.F. (factory & Colony)",
  "Pabbi", "Pabi", "Pachnand", "Paharpur", "Pak Pattan Sharif",
  "Pakka Laran", "Pakpattan", "Palandri", "Panjan Sher Shahana", "Pano Akil",
  "Panoaqil", "Paroa", "Pasni", "Pasroor", "Pasrur",
  "Pathika", "Patoki", "Patriata", "Pattoki", "Peer Mahal",
  "Peshawar", "Pezu", "Phagwari", "Phalia", "Phool Nagar",
  "Pinanwal", "Pind Dadan Khan", "Pindi Bhatian", "Pindi Gheb", "Pindi Gujran",
  "Pindi Point", "Pindi Said Pur", "Piplan", "Pir Baba", "Pir Jo Goth",
  "Pir Wasan", "Pira Fatehal", "Pirjogoth", "Piryaloi", "Pishin",
  "Pitaro", "Pma Kakul", "Poonch (AJK)", "Poranwala", "Pungirayin",
  "Punjar", "Punwan", "Puraan", "Qabal", "Qaboola Sharif",
  "Qadir Pur Rawan", "Qaidabad", "Qaim Bharwana", "Qaimpur", "Qalat",
  "Qamar Abad", "Qamar Mashani", "Qambar", "Qasba Gujrat.", "Qasimpura",
  "Qazi Ahmed", "Qila Ahmed Abad", "Qila Deedar Sing", "Qila Kalar Wala", "Qila Saib Singh",
  "Qila Sheikhupura", "Quetta", "Rabat", "Rachna Town", "Radhan",
  "Rahim Yar Khan", "Rahimyar Khan", "Raiwind", "Raja Jang", "Rajana",
  "Rajanpur", "Rajar", "Rakh Baloch Kalan", "Ramak", "Rani Pur",
  "Rao Khan Wala", "Rashaki", "Rasool Nagar", "Rato Dearo", "Ratodero",
  "Rawalakot", "Rawalakot (AJK)", "Rawalpindi", "Rawat", "Renala Khurd",
  "Risalpur", "Rohri", "Roundu", "Rubwa", "Rukkan",
  "Sabaz Peer", "Sadat Pur", "Sadiqabad", "Sadpara", "Safdarabad",
  "Saghar Pur", "Saharan Chattha", "Sahiwal", "Said Nagar", "Said Pur Gondal",
  "Saidu Shairf", "Saidu Sharif", "Sajawal", "Sakrand", "Sallhoke Chattha",
  "Samandari", "Samar Bagh", "Samaro", "Sambrial", "Samote",
  "Samundri", "Sanghar", "Sangla Hill", "Sangwala", "Sanjhoro",
  "Sanjwal", "Sarai Alamgir", "Sarai Mughal", "Saraye Norang", "Sardar Garh",
  "Sardaryab", "Sargodha", "Sari Alamgir", "Saroba", "Saroki Cheema",
  "Satrah", "Satyyana", "Sauwal", "Sawabi", "Sawari",
  "Sehr Bagla", "Sehwan Sharif", "Sermik", "Setharja", "Shabqadar",
  "Shadad Kot", "Shadan Lund", "Shadiwal", "Shah Bagh", "Shah Pur Chakar",
  "Shahdad Pur", "Shahdadpur", "Shahdara Town", "Shahkot", "Shahpur Jahania",
  "Shahpur Saddar", "Shakargarh", "Shakirila", "Sham Kot", "Shams Abad",
  "Shangla", "Sharaqpur Sharif", "Sharif Medical City", "Sheedo", "Sheikhoo Sugar Mills",
  "Sheikhu Chak", "Sheikhupura", "Shergarh", "Sheringal", "Shewa Adda",
  "Shigar", "Shikarpur", "Shimla Hill", "Shokhdara", "Shorkot",
  "Shorkot Cantonment", "Shujabad", "Sialkot", "Sibi", "Sihala",
  "Sikandarabad", "Silanwali", "Sinjhoro", "Sir Suba Shah", "Siraye Muhajir",
  "Sivia", "Skardu", "Smaal Ind Estate. Daska", "Sohawa", "Sohawa Only Main Gt Road",
  "Sokar", "Sudhanoti (AJK)", "Sui", "Sui Town", "Sukhu Chak",
  "Sukkur", "Sumbrial", "Sundar Industrial Estate", "Sunder Adda", "Surkhpur",
  "Swabi", "Swat", "Syed Wala", "T.T Singh", "Taja Bara",
  "Takht-e-bhai", "Takht-i-bahi", "Talagang", "Talagung", "Talash",
  "Talhar", "Tall", "Talpur Wada", "Talvandi", "Tamman",
  "Tandliawala", "Tando Adam", "Tando Allahyar", "Tando Bago", "Tando Ghulam Ali",
  "Tando Jam", "Tando Jan Muhammad", "Tando Mohd Khan", "Tangi", "Tank",
  "Tarbela Dam", "Tarnol", "Taunsa Sharif", "Taxila", "Taxla",
  "Tehi", "Thari Mirwah", "Thatha Amir", "Thatta", "Theeng More (allahabad)",
  "Thoa Mehram Khan", "Thoha Khalsa", "Thul", "Thul Hamza", "Thull",
  "Tibba Sultanpura", "Timargara", "Timargarah", "Tirat", "Toba Tek Singh",
  "Tobah", "Topa Adam", "Topi", "Topi (gik University Area Only)*", "Torwarsak",
  "Tranda Mohammad Panah", "Tranda Saway Khan", "Tret", "Tulamba", "Turbat",
  "Ubaro", "Ubauro", "Uch Shrif", "Uggoke", "Umar Kot",
  "Umerkot", "Upper Archer", "Upper Dir", "Usta Mohammad", "Usta Muhammad",
  "Uthal", "Vehari", "Verpal Chattha", "Village Sial", "Wada Machhi",
  "Wah CANTT.", "Wah Cantt", "Wahndo", "Wahova", "Wan Rahda Ram",
  "Wapda Colony (AJK)", "Warbattan", "Warraichan Wala", "Waryam Wala", "Wazir Ke Chattha",
  "Wazirabad", "Winder", "Yazman", "Zafarwal", "Zahir Pir",
  "Zhob"
];